#ifndef _lpc17xx_hal_h_
#define _lpc17xx_hal_h_

#ifdef __cplusplus
extern "C" {
#endif

#include "LPC17xx.h"
#include "clock_lpc17xx.h"
#include "pwr_lpc17xx.h"
#include "i2s_lpc17xx.h"
#include "i2c_lpc17xx.h"
#include "spi_lpc17xx.h"
#include "gpio_lpc17xx.h"
#include "uart_lpc17xx.h"
#include "dma_lpc17xx.h"
#include "dac_lpc17xx.h"
#include "adc_lpc17xx.h"
#include "tim_lpc17xx.h"
#include "rit_lpc17xx.h"

#define SET_BIT(REG, BIT)       ((REG) |= (BIT))
#define CLEAR_BIT(REG, BIT)     ((REG) &= ~(BIT))

#define PCONP_I2C0_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCI2C0)
#define PCONP_I2C1_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCI2C1)
#define PCONP_I2C2_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCI2C2)
#define PCONP_SPI_ENABLE      SET_BIT(LPC_SC->PCONP, SC_PCONP_PCSPI)
#define PCONP_SSP0_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCSSP0)
#define PCONP_SSP1_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCSSP1)
#define PCONP_UART0_ENABLE    SET_BIT(LPC_SC->PCONP, SC_PCONP_PCUART0)
#define PCONP_UART1_ENABLE    SET_BIT(LPC_SC->PCONP, SC_PCONP_PCUART1)
#define PCONP_UART2_ENABLE    SET_BIT(LPC_SC->PCONP, SC_PCONP_PCUART2)
#define PCONP_UART3_ENABLE    SET_BIT(LPC_SC->PCONP, SC_PCONP_PCUART3)
#define PCONP_GPDMA_ENABLE    SET_BIT(LPC_SC->PCONP, SC_PCONP_PCGPDMA)
#define PCONP_ADC_ENABLE      SET_BIT(LPC_SC->PCONP, SC_PCONP_PCADC)
#define PCONP_TIM0_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCTIM0)
#define PCONP_TIM1_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCTIM1)
#define PCONP_TIM2_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCTIM2)
#define PCONP_TIM3_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCTIM3)
#define PCONP_RIT_ENABLE      SET_BIT(LPC_SC->PCONP, SC_PCONP_PCRIT)
#define PCONP_RTC_ENABLE      SET_BIT(LPC_SC->PCONP, SC_PCONP_PCRTC)
#define PCONP_PWM1_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCPWM1)
#define PCONP_CAN1_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCCAN1)
#define PCONP_CAN2_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCCAN2)
#define PCONP_GPIO_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCGPIO)
#define PCONP_MCPWM_ENABLE    SET_BIT(LPC_SC->PCONP, SC_PCONP_PCMCPWM)
#define PCONP_QEI_ENABLE      SET_BIT(LPC_SC->PCONP, SC_PCONP_PCQEI)
#define PCONP_I2S_ENABLE      SET_BIT(LPC_SC->PCONP, SC_PCONP_PCI2S)
#define PCONP_ENET_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCENET)
#define PCONP_USB_ENABLE      SET_BIT(LPC_SC->PCONP, SC_PCONP_PCUSB)

#ifdef __cplusplus
}
#endif

#endif